export var products = [

  {
    id: 1,
    img: "../images/item/1.png",
    name: "جمبري كاري",
    price: 5.5,
    cart: false,
    quantity: 1,
    total: 0,
    class:"sea",
    Describe:"قطع جمبري مع صوص الكاجو والكاري كريمة",
  },

  {
    id: 2,
    img: "../images/item/2.png",
    name: "جمبري زبدة",
    price: 5.5,
    cart: false,
    quantity: 1,
    total: 0,
    class:"sea",
    Describe:"قطع جمبري مع زبدة وصوص الكاجو، كريمة",
  },
  {
    id: 3,
    img: "../images/item/3.png",
    name: "دجاج مسلا",
    price: 3.75,
    cart: false,
    quantity: 1,
    total: 0,
    class:"chicken",
    Describe:"دجاج مطبوخ بصلصة الطماطم والتوابل الهندية المميزة",
  },
  {
    id: 4,
    img: "../images/item/4.png",
    name: "دجاج بزبدة",
    price: 3.75,
    cart: false,
    quantity: 1,
    total: 0,
    class:"chicken",
    Describe:"دجاج مع الكريمة بالزبدة مطبوخ بالتوابل الهندية",
  },
  {
    id: 5,
    img: "../images/item/5.png",
    name: "دجاج تشيلي",
    price: 4.0,
    cart: false,
    quantity: 1,
    total: 0,
    class:"chicken",
    Describe:"دجاج بالفلفل الحار مقلي مع تتبيلة البهارات الهندية والزنجبيل",
  },
  {
    id: 6,
    img: "../images/item/6.png",
    name: "دجاج بالكاري",
    price: 4.0,
    cart: false,
    quantity: 1,
    total: 0,
    class:"chicken",
    Describe:"قطع جمبري مع صوص الكاجو والكاري، كريمة",
  },
  {
    id: 7,
    img: "../images/item/7.png",
    name: "دجاج دوبيازا",
    price: 4.0,
    cart: false,
    quantity: 1,
    total: 0,
    class:"chicken",
    Describe:"دجاج بالبصل والجبنة والفلفل الحلو مع الكريمة مطبوخ بالتوابل الهندية",
  },
  {
    id: 8,
    img: "../images/item/8.png",
    name: "تيكا ماسلا",
    price: 4.0,
    cart: false,
    quantity: 1,
    total: 0,
    class:"chicken",
    Describe:"دجاج مطبوخ بصلصة الطماطم والتوابل الهندية المميزة",
  },
  {
    id: 9,
    img: "../images/item/9.png",
    name: "دجاج جوز هند",
    price: 3.75,
    cart: false,
    quantity: 1,
    total: 0,
    class:"chicken",
    Describe:"دجاج بالبصل والجبنة والفلفل الحلو مع الكريمة مطبوخ بالتوابل الهندية",
  },
  {
    id: 10,
    img: "../images/item/10.png",
    name: "برياني جمبري",
    price: 5.0,
    cart: false,
    quantity: 1,
    total: 0,
    class:"chicken",
    Describe:"أرز برياني هندي مع قطع جمبري مقلية",
  },
  {
    id: 11,
    img: "../images/item/11.png",
    name: "برياني خضار",
    price: 2.0,
    cart: false,
    quantity: 1,
    total: 0,
    class:"rice",
    Describe:"أرز برياني هندي مع الخضار المشكل",
  },
  {
    id: 12,
    img: "../images/item/12.png",
    name: "برياني لحم",
    price: 4.5,
    cart: false,
    quantity: 1,
    total: 0,
    class:"rice",
    Describe:"أرز برياني هندي مع قطع اللحم",
  },
  {
    id: 13,
    img: "../images/item/13.png",
    name: "برياني دجاج",
    price: 3.5,
    cart: false,
    quantity: 1,
    total: 0,
    class:"rice",
    Describe:"أرز برياني هندي مع قطع الدجاج",
  },
  {
    id: 14,
    img: "../images/item/14.png",
    name: "ارز برياني",
    price: 1.25,
    cart: false,
    quantity: 1,
    total: 0,
    class:"rice",
    Describe:"أرز برياني هندي مع قطع الدجاج",
  },
  {
    id: 15,
    img: "../images/item/15.png",
    name: "ارز سادة",
    price: 0.75,
    cart: false,
    quantity: 1,
    total: 0,
    class:"rice",
    Describe:"أرز بسمتي بدون اضافات",
  },
  {
    id: 16,
    img: "../images/item/16.png",
    name: "برياني بيض",
    price: 2.25,
    cart: false,
    quantity: 1,
    total: 0,
    class:"rice",
    Describe:"أرز بسمتي مع البيض المسلوق",
  },
  {
    id: 17,
    img: "../images/item/17.png",
    name: "ارز كشمير بلاو",
    price: 3.0,
    cart: false,
    quantity: 1,
    total: 0,
    class:"rice",
    Describe:"أرز بسمتي،بازيلا مع كوكتيل فواكه",
  },
  {
    id: 18,
    img: "../images/item/18.png",
    name: "ارز بالاناناس",
    price: 2.25,
    cart: false,
    quantity: 1,
    total: 0,
    class:"rice",
    Describe:"أرز بسمتي بالزبدة مع قطع الأناناس",
  },
  {
    id: 19,
    img: "../images/item/19.png",
    name: "سندويشة سموكي تندوري",
    price: 1.5,
    cart: false,
    quantity: 1,
    total: 0,
    class:"sandwich",
    Describe:"دجاج مطبوخ بالكريمة والخلطة الهندية بخبزة باراتا ",
  },
  {
    id: 20,
    img: "../images/item/20.png",
    name: "سندويشة شاورما هندية",
    price: 1.0,
    cart: false,
    quantity: 1,
    total: 0,
    class:"sandwich",
    Describe:"شاورما على الطريقة الهندية",
  },
];